server:
  port: 8082
spring:
  rabbitmq:
    password: guest
    username: guest
    host: 127.0.0.1
    port: 5672
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/1804a
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
